spring.datasource.url=jdbc:mysql://localhost:3306/tennis_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.application.name=tennis-backend
server.port=8081
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
